### ISSUE TITLE
logout issue

### ISSUE THREAD

**Issue by StarryShark** [CloudGenix/sdk-nodejs#6]
There seems to be an issue with logout() method.

#### Code

```javascript
const CgSdk = require('cloudgenix');

const cgz = new CgSdk(
  process.env.CG_USERNAME,
  process.env.CG_PASSWORD, null, false
);

const main = async () => {
  try {
    await cgz.login();
  } catch (error) {
    console.error(error);
  }

  try {
    cgz.logout();
  } catch (error) {
    console.error(error);
  }
};

main();
```

#### Error

```shell
(node:9834) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_endpoints' of undefined
    at /Users/xxxxxxxxxxxxx/node_modules/cloudgenix/CloudGenixSdk.js:184:22
    at new Promise (<anonymous>)
    at CloudGenixSdk.logout (/Users/xxxxxxxxxxxxx/node_modules/cloudgenix/CloudGenixSdk.js:181:16)
    at main (/Users/xxxxxxxxxxxxx/test.js:17:9)
(node:9834) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9834) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please check.

**Comment by jchristn** [comment]
Hi @sumitgoelpw - thanks - I tracked this down and submitted v1.1.4 to npm with the appropriate fix.  Please let me know if any issues with it
